# fly.toml app configuration file generated for biff-docker on 2023-11-25T00:56:03-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "biff-docker"
primary_region = "sea"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
